###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.9'
services:
    app:
        image: php:8.0-apache
        container_name: app_send
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
            - 443:443
        links:
        - db
    db:
        image: mysql:latest
        container_name: database
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: appsend
        ports:
            - 3306:3306
    volumes:
        -   phpdocker 
